// "use client";

import "./globals.css";
import { Providers } from "./provides";

import { createConfig, http, WagmiProvider } from "wagmi";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
// import { config } from "./config";
import type { Metadata } from "next";
import { config } from "./config";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient()



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <WagmiProvider config={config}> */}
          {/* <QueryClientProvider client={queryClient}> */}
            <Providers>{children}</Providers>
          {/* </QueryClientProvider> */}
        {/* </WagmiProvider> */}
      </body>
    </html>
  );
}
